//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSouleymaneFaye.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovisionnementBis
    {
        public int idAppro { get; set; }
        public string CodeProduit { get; set; }
        public Nullable<int> QteAppro { get; set; }
        public Nullable<int> QteRestante { get; set; }
        public Nullable<System.DateTime> DatePeremption { get; set; }
        public Nullable<System.DateTime> DateAppro { get; set; }
    }
}
