//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSouleymaneFaye.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int idUt { get; set; }
        public string identifiantUt { get; set; }
        public string motDePasse { get; set; }
        public string codeProfil { get; set; }
    }
}
